# window
window.width=1920
window.height=1080
window.title=My LWJGL Game
window.vSync=true
window.horizontalFov=90

# shaders
path.shaders=res/shaders/
path.textures=res/textures/

# game settings
world.renderDistance=20
world.depth=3
world.isoLevel=100
world.chunkPerFrame = 4