# ????????? ????
window.width=1920
window.height=1080
window.title=My LWJGL Game
window.vSync=true
window.horizontalFov=90

# ???? ? ????????
path.shaders=res/shaders/
path.textures=res/textures/

# ????????? ????
world.renderDistance=10
world.depth=3
world.isoLevel=100